// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsovoafdrswgsdkghquk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhzb3ZvYWZkcnN3Z3Nka2docXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDA0NjgsImV4cCI6MjA2MTMxNjQ2OH0.V2bq0DfmPsJE2lf2IBSChtIPCm_6SAtJdfyMlk77i7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);